### ISSUE TITLE
Upgrade to fisherman?

### ISSUE THREAD

**Issue by ghost** [angstbear/omf-config#1]
Hi @angstbear 

I am no longer maintaining oh-my-fish, and the project has been kind of abandoned. I have moved to [fisherman](https://github.com/fisherman/fisherman) now, and I've been actively developing and supporting fish-shellers over there. I recommend upgrading :)

If you like the project, I would be glad to PR this repo or dotfiles to show you how to transition. Easy peasy.

Cheers.

**Comment by angstbear** [comment]
Thanks for reaching out to me, @bucaran. Fisherman actually looks awesome! I've been meaning to try for a while, and would definitely appreciate any tips or resources for transitioning.

**Comment by ghost** [comment]
@angstbear Absolutely. If you are on slack, http://join.fisherman.sh and ping me. I'll help you setup everything (it's super easy, literally drag fisher.fish into your fish functions directory, and you are done).
